spring:
  application:
    name: ninjaregister
  datasource:
    url: ${DATABASE_URL}
    driver: org.h2.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enable: true
    locations: 'classpath:db/migrations'
    baseline-on-migrate: true
